### PR TITLE
Allow specifying a custom label

### PR DESCRIPTION
**Pull request by fgilio**
Simple as that, allows specifying a custom label and bypass the automatically generated one.

This is useful if someone wants to use this in a language that's not English.

I first thought in translating it to Spanish, but then I realised that sometimes that wouldn't be enough. For example, in Spanish we need to specify the gender in adjectives and that can't be easily abstracted to work the same way "All" does in English. In Spanish you could say "Todos" or "Todas".

Even if that situation I described above is solved, I still think that the possibility of specifying a custom label is a neat addition.

### CODE REVIEW

**Comment by johnbillion** [comment]
Hey @fgilio, you can already specify labels via the `labels` argument.

Example:

```php
register_extended_post_type( 'foo', array(
  'labels' => array(
    'all_items' => 'Todos items',
    ...
  )
);
```

Let me know if this works as expected!

**Comment by fgilio** [comment]
Hi @johnbillion!

You sure about `register_extended_post_type `? I'm talking about a Custom Taxonomy here.

I've tryed this code but the label for `all_items` is still the automagically generated one `All Géneros`:
```
register_extended_taxonomy( 'genero', 'pelicula', [],
  [
  'singular'                   => 'Género',
  'plural'                     => 'Géneros',
  'all_items'                  => 'Todos',
  'parent_item'                => 'Género padre',
  'parent_item_colon'          => 'Género padre:',
  'new_item_name'              => 'Nombre del nuevo Género',
  'add_new_item'               => 'Agregar',
  'edit_item'                  => 'Editar',
  'update_item'                => 'Actualizar',
  'view_item'                  => 'Ver',
  'separate_items_with_commas' => 'Separar items con comas',
  'add_or_remove_items'        => 'Agregar o eliminar',
  'choose_from_most_used'      => 'Más usados',
  'popular_items'              => 'Populares',
  'search_items'               => 'Buscar',
  'not_found'                  => 'No se encontró nada',
  'no_terms'                   => 'No hay Géneros',
  'items_list'                 => 'Items list',
  'items_list_navigation'      => 'Items list navigation',
  ] );
```

**Comment by johnbillion** [comment]
Ah sorry I didn't check the repo name! :-)

Yes this still works. Your example code is missing the `labels` key, and it goes into the second argument, not the third. I will add some examples to the documentation to make this clear.

```php
register_extended_taxonomy( 'genero', 'pelicula', [
  'labels' => [
    'singular'                   => 'Género',
    'plural'                     => 'Géneros',
    'all_items'                  => 'Todos',
    'parent_item'                => 'Género padre',
    'parent_item_colon'          => 'Género padre:',
    'new_item_name'              => 'Nombre del nuevo Género',
    'add_new_item'               => 'Agregar',
    'edit_item'                  => 'Editar',
    'update_item'                => 'Actualizar',
    'view_item'                  => 'Ver',
    'separate_items_with_commas' => 'Separar items con comas',
    'add_or_remove_items'        => 'Agregar o eliminar',
    'choose_from_most_used'      => 'Más usados',
    'popular_items'              => 'Populares',
    'search_items'               => 'Buscar',
    'not_found'                  => 'No se encontró nada',
    'no_terms'                   => 'No hay Géneros',
    'items_list'                 => 'Items list',
    'items_list_navigation'      => 'Items list navigation',
  ]
] );
```

**Comment by fgilio** [comment]
Oohh I see, thank you!

**Pull request closed without merging**
