### PR TITLE
Mark custom taxonomy required while declaring

### PR DESCRIPTION
**Pull request by kala725**

### CODE REVIEW

**Comment by kala725** [comment]
@johnbillion  : As per the discussion with Ryan, This is going to be merged. May I know a timeline for it ?

**Comment by johnbillion** [comment]
Thanks for the patch, @kala725.

I thought Ryan was referring to #28 which was just merged :-)

Can you confirm that this works as expected? The default value for the dropdown is `-1`, therefore the `required` attribute has no effect because there is no empty value available in the dropdown, and therefore no value available that will trigger the browser's blocking behaviour when a required field is missing a value.

**Comment by kala725** [comment]
@johnbillion  :  As far as I understood your comment, you are talking about the case when there are no terms under the taxonomy.

If so, then it is intended that if one has marked the taxonomy required  while declaring the taxonomy and  has not added any terms , then it should block the form submission. Which is the intended behaviour of using the required attribute.

If you are talking about something else, please describe.

**Comment by johnbillion** [comment]
I'm talking about the case when there _are_ terms under the taxonomy. There's no condition under which the select menu has an empty option, so the `required` attribute has no effect because there's no `option` which has an empty value.

Here's the generated markup for a taxonomy containing three terms and with the `required` attribute. You'll note that the first option has a value of `-1`.

```html
<select required name="tax_input[taxo-program]" id="taxo-programdropdown" class="postform">
	<option value="-1">No program</option>
	<option class="level-0" value="2">one</option>
	<option class="level-0" value="5">three</option>
	<option class="level-0" value="4">two</option>
</select>
```

Can you provide an example which results in an empty option being present in the select menu?

**Comment by kala725** [comment]
Hi @johnbillion : Thanks for the feedback.
As per the line 709 on extended-taxos.php
`'option_none_value' => ( is_taxonomy_hierarchical( $taxonomy ) ? '-1' : '' ), `

So for all non hierarchical taxonomies, the first value is empty, making a case for this feature. The Select element, that you have referred to in the above comment, is one having hierarchical taxonomies.


Just out of curiosity, Why you are setting the default value (option_none value) to -1 for hierarchical taxonomies, So if needed, I can change this line to accommodate the required field. (In case , if required is set to true, it will skip this step.)


This is the html for non-hierarchical taxonomy select box.
```
<select required="" name="tax_input[article_format]" id="article_formatdropdown" class="postform">
	<option value="">No article format</option>
	<option class="level-0" value="Text">Text</option>
	<option class="level-0" value="Video" selected="selected">Video</option>
</select>
```

**Comment by johnbillion** [comment]
Ah-ha, I hadn't checked the behaviour for a non-hierarchical taxonomy. Thanks. I'll check it shortly.

The value of `-1` is needed for hierarchical taxonomies so WordPress correctly removes all the terms if a term was previously selected and you switch back to not selecting a term.

**Comment by kala725** [comment]
@johnbillion  : As we are talking about the only the dropdown here, does it makes sense to have `'option_none_value' => null,` as there will be single selection and It works as expected. Please let me know your inputs.

**Comment by johnbillion** [comment]
I've merged this in, thanks. I'll have a think about the `option_none_value` argument at a later date.

**Comment by kala725** [comment]
@johnbillion : Thanks for merging the PR. Soon, I will raise an another PR for marking required in the hierarchical taxonomies, once I am done with the testing of the said feature.

**Pull request closed without merging**
