### PR TITLE
Autoload the library

### PR DESCRIPTION
**Pull request by vinkla**
Autoload the extended-taxos.php file with composer.

### CODE REVIEW

**Comment by vinkla** [comment]
Pushed a new commit which checks if the `Walker` class exists or not. 

This fixes #20

**Comment by johnbillion** [comment]
That means the Walkers won't load and a big chunk of the functionality of the library won't work. Please test your changes.

**Comment by vinkla** [comment]
I've tested this in a current project and it works fine. This is only so it wont trigger when you autoload. Otherwise it will work as normal.

**Comment by johnbillion** [comment]
The change means that all three of those classes do not get declared because the `Walker` class does not exist at the point the file is being autoloaded. The classes are used for displaying different meta boxes when the `meta_box` argument for the taxonomy is changed (for example `'meta_box' => 'dropdown'`).

The proper solution is probably to separate the library into multiple files, with one class per file, so the classes can actually be autoloaded on demand, but I don't have the time to work on this at the moment.

**Comment by ekandreas** [comment]
Agree with the autoload problem and Walker. 
Curious why autoload isn't included in the package. It's the same with ecpt.

**Comment by vinkla** [comment]
Okay, to bad. Let me know if there is anything I can do to help speed this up.

**Pull request closed without merging**
